import { Badge } from "@/components/ui/badge";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";
import { cn } from "@/lib/utils";
import { ChevronDown, ChevronUp, Info, Shield, ShieldAlert, ShieldCheck } from "lucide-react";
import { useState } from "react";

interface TrustMetricsData {
    fact_accuracy: number;
    bias_level: number;
    reliability: number;
    objectivity: number;
    source_quality: number;
    community_relevance: number;
    overall_score: number;
    analysis_rationale?: string;
}

interface TrustMetricsProps {
    metrics: TrustMetricsData;
}

const metricInfo = {
    fact_accuracy: {
        label: "Fact Accuracy",
        description: "How accurate the factual claims in this article are based on verification",
    },
    bias_level: {
        label: "Neutrality",
        description: "How balanced and unbiased the article's presentation is",
    },
    reliability: {
        label: "Reliability",
        description: "How reliable the information sources and data appear to be",
    },
    objectivity: {
        label: "Objectivity",
        description: "The degree to which content is factual vs opinionated",
    },
    source_quality: {
        label: "Source Quality",
        description: "Quality assessment of the information sources used",
    },
    community_relevance: {
        label: "Local Relevance",
        description: "How relevant this story is to the local community",
    },
};

function getScoreColor(score: number): string {
    if (score >= 80) return "text-green-600 dark:text-green-400";
    if (score >= 60) return "text-yellow-600 dark:text-yellow-400";
    return "text-red-600 dark:text-red-400";
}

function getScoreBgColor(score: number): string {
    if (score >= 80) return "bg-green-50 dark:bg-green-950/30 border-green-200 dark:border-green-800";
    if (score >= 60) return "bg-yellow-50 dark:bg-yellow-950/30 border-yellow-200 dark:border-yellow-800";
    return "bg-red-50 dark:bg-red-950/30 border-red-200 dark:border-red-800";
}

function getBarColor(score: number): string {
    if (score >= 80) return "bg-green-500";
    if (score >= 60) return "bg-yellow-500";
    return "bg-red-500";
}

function ScoreBar({ score, label }: { score: number; label: string }) {
    return (
        <div className="flex items-center gap-2">
            <span className="w-28 shrink-0 text-xs text-muted-foreground">{label}</span>
            <div className="flex-1 h-2 bg-muted rounded-full overflow-hidden">
                <div className={cn("h-full rounded-full transition-all", getBarColor(score))} style={{ width: `${score}%` }} />
            </div>
            <span className={cn("w-8 text-xs font-medium text-right", getScoreColor(score))}>{score}</span>
        </div>
    );
}

export function TrustMetrics({ metrics }: TrustMetricsProps) {
    const [expanded, setExpanded] = useState(false);

    const ShieldIcon = metrics.overall_score >= 80 ? ShieldCheck : metrics.overall_score >= 60 ? Shield : ShieldAlert;

    const getBadgeVariant = () => {
        if (metrics.overall_score >= 80) return "success";
        if (metrics.overall_score >= 60) return "secondary";
        return "destructive";
    };

    return (
        <div className={cn("rounded-lg border p-4 mb-6", getScoreBgColor(metrics.overall_score))}>
            <div className="flex items-center justify-between">
                <div className="flex items-center gap-3">
                    <ShieldIcon className={cn("size-6", getScoreColor(metrics.overall_score))} />
                    <div>
                        <div className="flex items-center gap-2">
                            <span className="font-semibold text-sm">AI Trust Score</span>
                            <Tooltip>
                                <TooltipTrigger>
                                    <Info className="size-3.5 text-muted-foreground" />
                                </TooltipTrigger>
                                <TooltipContent className="max-w-xs">
                                    <p>This article was generated by AI and analyzed for trustworthiness across multiple dimensions.</p>
                                </TooltipContent>
                            </Tooltip>
                        </div>
                        <span className="text-xs text-muted-foreground">AI-generated content transparency</span>
                    </div>
                </div>
                <div className="flex items-center gap-3">
                    <Badge variant={getBadgeVariant()} className="text-lg px-3 py-1">
                        {metrics.overall_score}/100
                    </Badge>
                    <button
                        onClick={() => setExpanded(!expanded)}
                        className="text-muted-foreground hover:text-foreground transition-colors p-1"
                        aria-label={expanded ? "Collapse details" : "Expand details"}
                    >
                        {expanded ? <ChevronUp className="size-5" /> : <ChevronDown className="size-5" />}
                    </button>
                </div>
            </div>

            {expanded && (
                <div className="mt-4 pt-4 border-t border-border/50 space-y-3">
                    {(Object.keys(metricInfo) as Array<keyof typeof metricInfo>).map((key) => (
                        <Tooltip key={key}>
                            <TooltipTrigger className="w-full text-left">
                                <ScoreBar score={metrics[key]} label={metricInfo[key].label} />
                            </TooltipTrigger>
                            <TooltipContent>
                                <p>{metricInfo[key].description}</p>
                            </TooltipContent>
                        </Tooltip>
                    ))}

                    {metrics.analysis_rationale && (
                        <p className="text-xs text-muted-foreground mt-3 pt-3 border-t border-border/50 italic">{metrics.analysis_rationale}</p>
                    )}
                </div>
            )}
        </div>
    );
}
